### ISSUE TITLE
Add the db link

### ISSUE THREAD

**Issue by Hikari-Tsai** [SeungHeonDoh/msd-subsets#1]
Hi, Seung,
Thanks for your work about constract this repo.
I spend must time to find out the track_metadata.db, so maybe you can consider that add below code in README to remind others their need download this db from MSD.
`cd dataset`
`wget http://millionsongdataset.com/sites/default/files/AdditionalFiles/track_metadata.db`
Cheers!
Hikari

**Comment by seungheondoh** [comment]
Oh....! I forget this thing thanks! @Hikari-Tsai
