### ISSUE TITLE
Loading audio files

### ISSUE THREAD

**Issue by PabloPeso** [SeungHeonDoh/msd-subsets#2]
Hi,

Thanks for your work. I understand you we don't provide directly audio data in this page due to copyright issues. However I was wondering how you would get the audio data. The [example code](https://github.com/seungheondoh/msd-subsets/tree/master#dataset-loader-for-classification) provided is expecting the audio files in the path `dataset/npy/5/9/5975357.clip.npy`. How can we get this data? Any directions/tips?

Thanks,

Pablo Peso.

**Comment by seungheondoh** [comment]
If you need MSD audio, please send email to seungheondoh@kaist.ac.kr

**Comment by wwfcnu** [comment]
> If you need MSD audio, please send email to [seungheondoh@kaist.ac.kr](mailto:seungheondoh@kaist.ac.kr)

@seungheondoh I sent the email, please check it when you have time

**Comment by nairanish1** [comment]
@seungheondoh I have also sent an email, please check at your earliest convenience

**Comment by kqwyf** [comment]
@seungheondoh I also sent an email, would you kindly take a look when you have a moment? Thank you!
