### ISSUE TITLE
msd-subsets dataset

### ISSUE THREAD

**Issue by wwfcnu** [SeungHeonDoh/msd-subsets#3]
Could you please provide the dataset?

**Comment by seungheondoh** [comment]
please send request e-mail to seungheondoh@kaist.ac.kr !

**Comment by wwfcnu** [comment]
I've already sent an email, so you can check your email when you have time



---- Replied Message ----
| From | Seungehon ***@***.***> |
| Date | 09/20/2023 12:14 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [seungheondoh/msd-subsets] msd-subsets dataset (Issue #3) |

please send request e-mail to ***@***.*** !

**Comment by seungheondoh** [comment]
@wwfcnu Oh... I cannot find your email in the above email.
Could you send mail again with your purpose and affiliation?

**Comment by wwfcnu** [comment]
> @wwfcnu Oh... I cannot find your email in the above email. Could you send mail again with your purpose and affiliation?

@seungheondoh I resent it, please take a look again，thanks
<img width="775" alt="image" src="https://github.com/seungheondoh/msd-subsets/assets/109075309/02aac999-5a32-4db9-965b-efbb16887069">
